/*
 * Copyright (c) 2026 Guadalupe Garcia <guad.daniel.garcia@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not,
 * see <https://www.gnu.org/licenses/>.
 */
package com.guavasoft.agentcompass.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;

/**
 * The latest local-Ollama analysis of one trace. {@code traceId} is the primary key rather than a
 * surrogate id — this table stores latest-only, so a regenerate is a plain upsert on the same key.
 */
@Entity
@Getter
@Setter
@Table(name = "trace_analyses")
public class TraceAnalysisEntity {

    @Id
    @Column(name = "trace_id", length = 32)
    private String traceId;

    @Column(name = "model", nullable = false)
    private String model;

    @Column(name = "analysis_text", nullable = false, columnDefinition = "text")
    private String analysisText;

    @Column(name = "generation_duration_ms", nullable = false)
    private long generationDurationMs;

    @Column(name = "generated_at", nullable = false)
    private Instant generatedAt;

    /**
     * {@code MAX(end_timestamp)} across the trace's spans as of generation -- lets a later read
     * detect that the trace has picked up new spans since (see {@code TraceAnalysisService}).
     */
    @Column(name = "last_span_end_timestamp", nullable = false)
    private Instant lastSpanEndTimestamp;

    /**
     * The human-written request this analysis judged, exactly as it was typed -- the "before" half
     * of the Better wording card. <b>Nullable</b>: a slash command, a {@code <task-notification>}
     * envelope and a sub-agent run carry no wording anyone authored, which is precisely when the
     * review drops its request-quality half, and every row stored before this column existed is
     * null too.
     */
    @Column(name = "user_prompt", columnDefinition = "text")
    private String userPrompt;

    /**
     * <b>Historical only.</b> No analysis generated after {@code V28} sets this {@code true} — the
     * timeline is now partitioned into consecutive, non-overlapping windows (see {@link
     * #reviewPassCount}) rather than elided. A row written by an earlier build may still carry
     * {@code true} truthfully.
     */
    @Column(name = "timeline_truncated", nullable = false)
    private boolean timelineTruncated;

    /**
     * <b>Historical only</b>, for the same reason as {@link #timelineTruncated} — see {@code V28}'s
     * migration comment. Lines, not raw calls, on the rows that carry a nonzero value.
     */
    @Column(name = "omitted_line_count", nullable = false)
    private int omittedLineCount;

    /**
     * How many review windows (model calls that wrote findings) this analysis was generated from —
     * see {@code TraceAnalysisPromptBuilder#partitionToBudget}. {@code 1} for an ordinary trace and
     * for every row written before {@code V28}.
     */
    @Column(name = "review_pass_count", nullable = false)
    private int reviewPassCount = 1;

    /**
     * The trace's total call count, unaffected by how many review windows it took — {@code 0} for a
     * row written before {@code V28} never computed one.
     */
    @Column(name = "timeline_call_count", nullable = false)
    private int timelineCallCount;

    /**
     * A plain-text "what happened" recap — request, work, outcome — composed in code, never sent to
     * Ollama. <b>Nullable</b>: every row written before {@code V26} was generated by a build that
     * never computed one.
     */
    @Column(name = "summary", columnDefinition = "text")
    private String summary;
}
