-- Initial schema for agent-compass. Mirrors the three OTLP signal types:
--   metric_points  ← MetricPointEntity   (POST /v1/metrics)
--   log_records    ← LogRecordEntity     (POST /v1/logs)
--   spans          ← SpanEntity          (POST /v1/traces)
--
-- jsonb columns hold OTLP attribute bags (resource / scope / data-point level)
-- so report SQL can filter and group without schema changes when new agent
-- attributes appear.

CREATE TABLE metric_points (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name         varchar(255) NOT NULL,
    unit                varchar(255),
    description         varchar(1024),
    scope_name          varchar(255),
    timestamp           timestamp(6) with time zone NOT NULL,
    start_timestamp     timestamp(6) with time zone,
    value_double        float8,
    value_long          bigint,
    value_kind          varchar(255),
    attributes          jsonb,
    resource_attributes jsonb,
    scope_attributes    jsonb,
    received_at         timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_metric_points_name_ts ON metric_points (metric_name, timestamp);
CREATE INDEX idx_metric_points_ts      ON metric_points (timestamp);

CREATE TABLE log_records (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp           timestamp(6) with time zone NOT NULL,
    observed_timestamp  timestamp(6) with time zone,
    severity_number     integer,
    severity_text       varchar(255),
    body                text,
    scope_name          varchar(255),
    trace_id            varchar(32),
    span_id             varchar(16),
    attributes          jsonb,
    resource_attributes jsonb,
    scope_attributes    jsonb,
    received_at         timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_log_records_ts       ON log_records (timestamp);
CREATE INDEX idx_log_records_severity ON log_records (severity_number, timestamp);
CREATE INDEX idx_log_records_trace    ON log_records (trace_id);

CREATE TABLE spans (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id            varchar(32) NOT NULL,
    span_id             varchar(16) NOT NULL,
    parent_span_id      varchar(16),
    name                varchar(255) NOT NULL,
    kind                varchar(255),
    start_timestamp     timestamp(6) with time zone NOT NULL,
    end_timestamp       timestamp(6) with time zone NOT NULL,
    duration_nanos      bigint,
    status_code         varchar(255),
    status_message      varchar(255),
    scope_name          varchar(255),
    attributes          jsonb,
    events              jsonb,
    resource_attributes jsonb,
    scope_attributes    jsonb,
    received_at         timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_spans_trace      ON spans (trace_id);
CREATE INDEX idx_spans_start_ts   ON spans (start_timestamp);
CREATE INDEX idx_spans_name_start ON spans (name, start_timestamp);
