/*
 * Copyright (c) 2026 Guadalupe Garcia <guad.daniel.garcia@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not,
 * see <https://www.gnu.org/licenses/>.
 */
package com.guavasoft.agentcompass.model;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.Instant;
import java.util.List;

@Schema(description = "What is running and what schema it is running against. The application version "
        + "comes from META-INF/build-info.properties, generated by the spring-boot-maven-plugin's "
        + "build-info goal; the release workflow bumps the pom to a -SNAPSHOT version before packaging, "
        + "so a released image legitimately reports a snapshot suffix.")
public record SystemBuild(
        @Schema(description = "Maven project version, or 'dev' when build-info.properties is absent "
                + "(IDE-launched runs, which skip generate-resources)", example = "1.6.0-SNAPSHOT")
        String applicationVersion,

        @Schema(description = "When the jar was built, or null when build-info.properties is absent",
                example = "2026-08-22T18:31:04Z") Instant buildTime,

        @Schema(description = "Runtime.version() of the JVM serving this request", example = "21.0.5")
        String javaVersion,

        @Schema(description = "JVM vendor", example = "Eclipse Adoptium") String javaVendor,

        @Schema(description = "JVM name", example = "OpenJDK 64-Bit Server VM") String jvmName,

        @Schema(description = "Postgres server_version of the connected database. Packaged builds "
                + "append their distribution to it, so this is not always a bare major.minor.",
                example = "16.13 (Debian 16.13-1.pgdg13+1)") String postgresVersion,

        @Schema(description = "Every applied Flyway migration, most recent first")
        List<SchemaMigration> migrations) {
}
